# Generated by Django 3.1.7 on 2021-03-21 05:52

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210321_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория'),
        ),
    ]
