# Generated by Django 3.1.7 on 2021-03-21 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
        ('catalog', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.container', verbose_name='Контейнер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_account.supplier', verbose_name='Поставщик'),
        ),
    ]
